### PR TITLE
Add a sockstat package and use it to parse sockstat values

### PR DESCRIPTION
**Pull request by spraints**
Sockstat values have some weird formatting sometimes. Strings are just the value, but numbers have a "uint:" prefix and bools have a "bool:" prefix. This has caused a couple of problems in spokes-receive-pack already, so this branch introduces a `sockstat` package that provides helpers for parsing the correct values, along with decorating var names.

This is based on #67 because it also fixes a bug introduced there. Notably it does not fix the bug in `performReferenceDiscovery` that #67 is working on a fix for; the old code that accesses `os.Getenv("GIT_SOCKSTAT_VAR_...` directly will be removed later.

cc @migue

### CODE REVIEW

**Comment by migue** [comment]
Thanks a lot! I thought about changing it but I did end up not doing it because I wanted to minimize the number of introduced changes.

I think the `go.mod` file will need to point to a newer version in order to support the new method you've added

**Comment by spraints** [comment]
> Thanks a lot! I thought about changing it but I did end up not doing it because I wanted to minimize the number of introduced changes.

Yeah, this would be a bigger change. We can do it as a followup, if you'd prefer.

**Comment by spraints** [comment]
> I think the `go.mod` file will need to point to a newer version in order to support the new method you've added

Thanks! I rebased to include that in the `strings.CutPrefix` change.

**Comment by spraints** [comment]
> > I think the `go.mod` file will need to point to a newer version in order to support the new method you've added
> 
> Thanks! I rebased to include that in the `strings.CutPrefix` change.

This needed a bigger change (0bcc658cab004b5ba67dab1d6cae1ac9d86979c4) because CI was using an older version of Go (and of golangci-lint).

**Review by migue — APPROVED** [review]

**Pull request merged**
