### PR TITLE
Set up dependabot for Go

### PR DESCRIPTION
**Pull request by spraints**
I was looking at settings today and saw that Dependabot wasn't set up to update Go dependencies. This branch adds config for that.

### CODE REVIEW

**Comment by spraints** [comment]
I switched this to a draft PR while I sort out the problems with actions config here.

**Review by migue — APPROVED** [review]

**Comment by migue** [comment]
I think with the last couple of changes we should be good to go?

**Review by migue — APPROVED** [review]

**Comment by migue** [comment]
@spraints are you okay if we merge this?

**Comment by migue** [comment]
I talked to @spraints today and he is okay with moving this forward

**Pull request merged**
